<?php
/**
 * Created by PhpStorm.
 * User: seb
 * Date: 20/11/18
 * Time: 11:20
 */

namespace App\Form;
use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleSearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder ->add('searchField');
                 //->add('nameCategory');
        // parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

    }

   /* public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ArticleSearchType::class]);
        //parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }*/


}