<?php
/**
 * Created by PhpStorm.
 * User: seb
 * Date: 26/11/18
 * Time: 10:05
 */

namespace App\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
       // $category = new Category();

        $builder ->add('name');

       // parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(['data_class' => Category::class,
            ]);

        // parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }

}