<?php
/**
 * Created by PhpStorm.
 * User: seb
 * Date: 20/11/18
 * Time: 15:29
 */

namespace App\Form;


use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name');
        // parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

}